// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./Users/antfu/i/vitesse-webext/src/components/Logo.vue')['default']
  }
}

export { }
