// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./components/Logo.vue')['default']
    PixelarticonsPower: typeof import('virtual:vite-icons/pixelarticons/power')['default']
    PixelarticonsSliders: typeof import('virtual:vite-icons/pixelarticons/sliders')['default']
    PixelarticonsZap: typeof import('virtual:vite-icons/pixelarticons/zap')['default']
  }
}

export { }
